module.exports = {
    STATUS_PENDING: 1,
    STATUS_ACTIVE: 2,
    STATUS_INACTIVE: 3,
    STATUS_REJECTED: 4,
    STATUS_BLOCKED: 5,
    STATUS_VALIDATED: 6,
    STATUS_AUTHORIZED: 7,
    STATUS_PROCESSING: 8,
    STATUS_PROCESSED_SUCCESS: 9,
    STATUS_PROCESSED_FAILED: 10,
    STATUS_PROCESSED_TIMEOUT: 11,
    STATUS_PROCESSED_PARTIALLY: 12,
};
  